#Configuration file for Music Composition project

#epoch
medieval:

  #values associated with each epoch
  
  measureIntervals: ../textFiles/medieval/intervals/3_2_time.yaml
  
  measureDurations: ../textFiles/medieval/durations/3_2_time.yaml
    
  otherValues:
  
    era : Medieval
    range : 14
    defaultDuration : 4000
  
  
  
  
  
  
  
  
  
  
    
#******************************************************************
      
renaissance:

  intervalProbabilities:

    uni : 0.2571
    step : 0.4305
    third : 0.1061
    fourth : 0.0728
    fifth : 0.048
    sixth : 0.0048
    seventh : 0.0006
    octave : 0.0094
    rest : 0.1
    
  noteProbabilities:  
   
   
    sixteenthNote : 0.0073
    eighthNote : 0.1693
    dottedEighthNote : 0.00265
    sixthNote : 0.000046
    quarterNote : 0.4143
    dottedQuarterNote :  0.03311
    halfNote : 0.2767
    dottedHalfNote : 0.02215
    wholeNote : 0.0735
    dottedWholeNote : 0.000776
	thirdNote : 0.000045
      
  restProbabilities: 
   
    eighthRest : 0.025334
    quarterRest : 0.29983
    halfRest : 0.22773
    dottedHalfRest : 0.0626
    wholeRest : 0.3800
    dottedWholeRest : 0.00445
    
  otherValues:
  
    era : Renaissance
    range : 22
    defaultDuration : 4000
    
    
          
#**********************************************************************

baroque :

  intervalProbabilities:

    uni : 0.2623
    step : 0.3558
    third : 0.1114
    fourth : 0.0728
    fifth : 0.0442
    sixth : 0.0292
    seventh : 0.0108
    octave : 0.0379
    rest : 0.1
    
  noteProbabilities:  
  

    twentyForthNote : 0.006144
    sixteenthNote : 0.293385
    twelfthNote : 0.00584
    eighthNote : 0.37415
    dottedEighthNote : 0.183384
    quarterNote : 0.169800
    dottedQuarterNote :  0.013697 
    halfNote : 0.029199
    dottedHalfNote : 0.00658
    wholeNote : 0.008092
    dottedWholeNote : 0.0005955
	dottedEighthNote : 0.01833
	thirtysecondNote : 0.06562
	dottedSixteenthNote : 0.006825
	fortyEighthNote : 0.00170

      
  restProbabilities: 
   
    eighthRest : 0.1803
    quarterRest : 0.187
    halfRest : 0.1362
    dottedHalfRest : 0.1880
    wholeRest : 0.1675
    dottedWholeRest : 0.006865
	sixteenthRest : 0.02469
	dottedFourthRest : 0.10413
	thirtySecondRest : 0.004095
	dottedSixteenthRest : 0.00012045
	twentyFourthRest : 0.000241
    
  otherValues:
  
    era : Baroque
    range : 23
    defaultDuration : 4000
    
    
          
#********************************************************************************

classical :

  intervalProbabilities:

    uni : 0.148
    step : 0.3964
    third : 0.1713
    fourth : 0.0818
    fifth : 0.0574
    sixth : 0.0435
    seventh : 0.0195
    octave : 0.0353
    rest : 0.1
   
  noteProbabilities:  
  
    
    twentyForthNote : 0.04287 
    sixteenthNote : 0.3852
    twelfthNote : 0.0189
    eighthNote : 0.31433
    dottedEighthNote : 0.013465
    quarterNote : 0.12261
    dottedQuarterNote :  0.011675 
    halfNote : 0.0097225
    dottedHalfNote : 0.001383
    wholeNote : 0.00024408
    dottedEighthNote : 0.01346
	dottedSixteenthNote : 0.00419
	fortyEighthNote : 0.00122
	
      
  restProbabilities: 
   
    eighthRest : 0.552257
    quarterRest : 0.263115
    halfRest : 0.01586
    dottedHalfRest : 0.0052867
    wholeRest : 0.00162
	sixteenthRest : 0.101667
	dottedFourthRest : 0.02196
	thirtySecondRest : 0.01789
	dottedSixteenthRest : 0.00732
	twentyFourthRest : 0.0065
    
    
  otherValues:
  
    era : Classical
    range : 25
    defaultDuration : 4000

      
      
#************************************************************

romantic :

  intervalProbabilities:
  
    uni : 0.207
    step : 0.2791
    third : 0.1112
    fourth : 0.0649
    fifth : 0.0416
    sixth : 0.0282
    seventh : 0.0123
    octave : 0.0217
    rest : 0.1
    
  noteProbabilities:  
  
    
    twentyForthNote : 0.067937
    sixteenthNote : 0.202843
    twelfthNote : 0.101507
    eighthNote : 0.1589
    dottedEighthNote : 0.041305
    sixthNote : 0.0005709
    quarterNote : 0.230132
    dottedQuarterNote :  0.031628 
    halfNote : 0.04507
    dottedHalfNote : 0.012188
    wholeNote : 0.005280
    thirtySecondNote : 0.00196
	dottedSixteenthNote : 0.00941
	twentyFourthNote : 0.06793
	fourtyEighthNote : 0.00373
      
  restProbabilities: 
   
    eighthRest : 0.30659
    quarterRest : 0.41138
    halfRest : 0.1073
    dottedHalfRest : 0.03065
    wholeRest : 0.025619
    dottedWholeRest : 0.0023099
	sixteenthRest : 0.0424
	dottedQuarterRest : 0.0252
	thirtySecondRest : 0.00042
	twentyFourthRest : 0.001259
    
  otherValues:
  
    era : Romantic
    range : 30
    defaultDuration : 4000

      
      
#****************************************************************

modern:

  intervalProbabilities:

    uni : 0.3086
    step : 0.2153
    third : 0.1011
    fourth : 0.1053
    fifth : 0.0723
    sixth : 0.0591
    seventh : 0.0364
    octave : 0.0571
    rest : 0.1
    
  noteProbabilities:  
  
    
    twentyForthNote : 0.02642
    sixteenthNote : 0.038199
    twelfthNote : 0.2245
    eighthNote : 0.3543
    dottedEighthNote : 0.0009
    sixthNote : 0.006519
    quarterNote : 0.20112
    dottedQuarterNote : 0.03197 
    halfNote : 0.01664
    dottedHalfNote : 0.009893
    wholeNote : 0.00343112
    thirtySecondNote : 0.03047
	dottedSixteenthNote : 0.0002859
      
  restProbabilities: 
   
    eighthRest : 0.738878
    quarterRest : 0.144423
    halfRest : 0.0238
    dottedHalfRest : 0.00902
    wholeRest : 0.0199
    sixteenthRest : 0.00257
	thirtySecondRest : 0.03868
	twentyFourthRest : 0.0077 
	sixthRest : 0.00386
    
  otherValues:
  
    era : Modern
    range : 37
    defaultDuration : 4000

      
